// Generated by CoffeeScript 1.10.0
(function() {
  var object;

  object = typeof window !== "undefined" ? window : GLOBAL;

  if (typeof console !== "undefined" && console.log && _.isFunction(console.log)) {
    object.cl = _.bind(console.log, console);
  } else {
    object.cl = function() {};
  }

}).call(this);
