// Generated by CoffeeScript 1.7.1
(function() {
  var $body, isDebug;

  isDebug = false;

  $body = $(document.body);

  $body.arrive("[data-jsaction*='show_date_time_picker']", function() {
    var $element, $firstExistingLi, $newLi, $ul, firstExistingLiHtml, textContainers;
    $element = $(this);
    $ul = $element.closest("section").prev("section").find("ul");
    $firstExistingLi = $ul.find("li").first();
    firstExistingLiHtml = $firstExistingLi[0].outerHTML;
    $newLi = $(firstExistingLiHtml);
    $newLi.find().andSelf().each(function(index, el) {
      return $(el).removeAttr("id jsl jsan jsaction jsinstance data-jsaction data-action-data");
    });
    textContainers = [];
    $newLi.find("span").each(function(index, el) {
      var $el;
      $el = $(el);
      if ($el.text().trim()) {
        return textContainers.push($el);
      }
    });
    textContainers[0].text("Tomorrow noon");
    textContainers[1].text("4:00 PM");
    $newLi.addClass("snooze-li");
    $newLi.on("click", function(event) {
      $body.arrive("[jsaction*='show_date_picker'] + div", function() {
        var $currentTd, $targetTd, $tds, cls, tdsByClassNames;
        tdsByClassNames = {};
        $("[jsaction*='show_date_picker'] + div tbody td").each(function() {
          var $td, cls, clses, _i, _len, _results;
          $td = $(this);
          clses = $td.attr("class").toString().split(' ');
          _results = [];
          for (_i = 0, _len = clses.length; _i < _len; _i++) {
            cls = clses[_i];
            if (!tdsByClassNames[cls]) {
              tdsByClassNames[cls] = [];
            }
            _results.push(tdsByClassNames[cls].push($td));
          }
          return _results;
        });
        $currentTd = null;
        for (cls in tdsByClassNames) {
          $tds = tdsByClassNames[cls];
          if ($tds.length === 1) {
            $currentTd = $tds[0];
            break;
          }
        }
        if (!$currentTd) {
          throw "Couldn't find current td";
        }
        $targetTd = $currentTd.next();
        if (!$targetTd.length) {
          $targetTd = $currentTd.closest("tr").next().find("td").first();
        }
        $targetTd.simulate("click");
        return $body.unbindArrive("[jsaction*='show_date_picker'] + div");
      });
      $body.arrive("[jsaction*='show_time_picker'] input[value]", {
        fireOnAttributesModification: true
      }, function() {
        var $divAfterShowTimePicker, $input;
        $input = $(this);
        $divAfterShowTimePicker = $input.closest("[jsaction*='show_time_picker']").next();
        $divAfterShowTimePicker.arrive("[role='menuitem']", function() {
          if ($(this).text().trim() === "Custom") {
            $(this).simulate("mousedown").simulate("mouseup").simulate("click");
            $input.val("4:00 PM");
            $input.blur();
            _.defer(function() {
              return $("[jsaction*='date_time_pattern_set']").simulate("mousedown").simulate("mouseup").simulate("click");
            });
            return $divAfterShowTimePicker.unbindArrive("[role='menuitem']");
          }
        });
        $input.simulate("mousedown").simulate("mouseup").simulate("click");
        return $body.unbindArrive("[jsaction*='show_time_picker'] input[value]");
      });
      return $("[data-jsaction*='show_date_time_picker']").simulate("mousedown").simulate("mouseup").simulate("click");
    });
    $ul.append($newLi);
    if (isDebug) {
      return $newLi.simulate("click");
    }
  });

  if (isDebug) {
    $body.arrive(".top-level-item [jsaction*='list.toggle_snooze_menu']", function() {
      $(this).simulate("mousedown").simulate("mouseup").simulate("click");
      return $body.unbindArrive(".top-level-item [jsaction*='list.toggle_snooze_menu']");
    });
    $body.arrive(".top-level-item [jsaction*='list.toggle_item']", function() {
      $(".top-level-item [jsaction*='list.toggle_item']").first().simulate("mouseover");
      return $body.unbindArrive(".top-level-item [jsaction*='list.toggle_item']");
    });
  }

}).call(this);
